sim:
	iverilog -o echo_test -y ./ echo_testbench.v alu.v branch_comparator.v control.v imm_gen.v reg_file.v riscv.v mem/bios_mem.v mem/dmem.v mem/imem.v mem/csr.v mem/mmio.v hw/uart.v hw/uart_recv.v hw/uart_trans.v
